config/routes.rb
Rails.application.routes.draw do
  resources :twitts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "twitt#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/twitt.rb
class Twitt < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/twitts_controller.rb
class TwittsController < ApplicationController
  before_action :set_twitt, only: %i[ show edit update destroy ]

  # GET /twitts or /twitts.json
  def index
    @twitts = Twitt.all
  end

  # GET /twitts/1 or /twitts/1.json
  def show
  end

  # GET /twitts/new
  def new
    @twitt = Twitt.new
  end

  # GET /twitts/1/edit
  def edit
  end

  # POST /twitts or /twitts.json
  def create
    @twitt = Twitt.new(twitt_params)

    respond_to do |format|
      if @twitt.save
        format.html { redirect_to twitt_url(@twitt), notice: "Twitt was successfully created." }
        format.json { render :show, status: :created, location: @twitt }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @twitt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twitts/1 or /twitts/1.json
  def update
    respond_to do |format|
      if @twitt.update(twitt_params)
        format.html { redirect_to twitt_url(@twitt), notice: "Twitt was successfully updated." }
        format.json { render :show, status: :ok, location: @twitt }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @twitt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twitts/1 or /twitts/1.json
  def destroy
    @twitt.destroy

    respond_to do |format|
      format.html { redirect_to twitts_url, notice: "Twitt was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twitt
      @twitt = Twitt.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def twitt_params
      params.require(:twitt).permit(:username, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twitts_helper.rb
module TwittsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestTwitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/twitts/_form.html.erb
<%= form_with(model: twitt) do |form| %>
  <% if twitt.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(twitt.errors.count, "error") %> prohibited this twitt from being saved:</h2>

      <ul>
        <% twitt.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/twitts/_twitt.html.erb
<div id="<%= dom_id twitt %>">
  <p>
    <strong>Username:</strong>
    <%= twitt.username %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= twitt.description %>
  </p>

</div>

app/views/twitts/edit.html.erb
<h1>Editing twitt</h1>

<%= render "form", twitt: @twitt %>

<br>

<div>
  <%= link_to "Show this twitt", @twitt %> |
  <%= link_to "Back to twitts", twitts_path %>
</div>

app/views/twitts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Twitts</h1>

<div id="twitts">
  <% @twitts.each do |twitt| %>
    <%= render twitt %>
    <p>
      <%= link_to "Show this twitt", twitt %>
    </p>
  <% end %>
</div>

<%= link_to "New twitt", new_twitt_path %>

app/views/twitts/new.html.erb
<h1>New twitt</h1>

<%= render "form", twitt: @twitt %>

<br>

<div>
  <%= link_to "Back to twitts", twitts_path %>
</div>

app/views/twitts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @twitt %>

<div>
  <%= link_to "Edit this twitt", edit_twitt_path(@twitt) %> |
  <%= link_to "Back to twitts", twitts_path %>

  <%= button_to "Destroy this twitt", @twitt, method: :delete %>
</div>